create table users (
  id bigint generated by default as identity primary key,
  username varchar(64) not null unique,
  salt varchar(64) not null,
  password_hash_hex varchar(64) not null
);

create table resources (
  id bigint generated by default as identity primary key,
  path varchar(128) not null unique,
  max_volume int not null
);

create table permissions (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  resource_path varchar(128) not null,
  actions varchar(128) not null,
  constraint fk_perm_user foreign key (user_id) references users(id),
  constraint uk_perm unique (user_id, resource_path)
);
